import { Container } from '@mantine/core';

function BobaFett() {

    return (
        <>
            <Container>
                <p>It’s no secret that the recent Star Wars trilogy floundered a bit. It relied on mostly hype to appeal to large audiences while suffering from a disjointed story and characters that felt flat or underdeveloped. It was a sort of mix between a checklist and a badminton match between writers and directors, resulting in the story behind the Disney trilogy being more interesting than the trilogy’s story itself. We could go into how the trilogy struggled to become a new part of the Star Wars series, being a forced rehash of the original trilogy. We can explore how the prequel trilogy had its own charms, despite its flaws, just as the original trilogy did. We can discuss how a star cast and fantastic effects cannot make up for a lackluster story and a constant need to one-up the scale and magnitude of the previous films. But I won’t because everybody online has already done so.</p>

                <p>It was only with the Mandalorian that some executive realized Star Wars isn’t just a movie property, but a rich franchise with incredible potential. There are thousands of years of history, hundreds of potential stories to be told that don’t exclusively revolve around the Jedi and the Sith. The Force is not dark and light, but a spectrum of power and emotion that allows a variety of different cultures to experience it through different lenses and philosophies. No wonder the most interesting characters are those that tread that line. Darth Revan, the Hutt Jedi, the Mandalorians…they don’t fit in that Jedi/Sith box, but their stories are nevertheless enthralling.</p>

                <p>Which is why I find the Book of Boba Fett so great at the start. It ties back into the roots of the franchise, where sci-fi meets the classic spaghetti western inspired by samurai movies. It mostly takes place on Tatooine, which is a setting we’ve seen so many times…yet know so little about. In the mainstream movies, we just know it as the sand planet where the Skywalkers spend their formative years. It’s secluded and away from the influence of major governments, making it the best place for syndicates to hang around. An entire planet that’s lost by the wayside and easily forgotten, much like the settler towns of the Old West or villages of Warring States Japan. And we see that fully in Book of Boba Fett, whereas they had to tell us that in the other movies.</p>

                <p>The greatest crime Star Wars has done to the sci-fi genre is the homogenization of entire planets. City planet, swamp planet, ocean planet, desert planet…to Star Wars fans, I don’t even need to say their names. Book of Boba shifts the paradigm of ‘same planet, different locale’. From the tiny towns to the migrating scavengers, from the trading ports struggling under the yoke of gangs to the natives forced to become hostile to survive. It’s the same desert planet, but it’s become more. Tatooine was a dead planet in the original trilogy, a cage in the prequels, and almost a middle finger to the fans in the recent trilogy. But Book of Boba makes it feel alive, not simply a homogenous den of deserts, devils, and dastards.</p>

                <p>Which is why the latter part felt strange. It was rushed, as if the budget had run out. Or the plot had to be accelerated to reach not a satisfying conclusion, but one that would allow more story to be written. I don’t like the Disney Trilogy. As someone who’s easily entertained, it’s fine. As someone who loves stories, however, it is lacking. BUT, one of the best things about it is that it ended. The Skywalker saga has a beginning, middle, and end. One family, one person cannot dominate the narrative of a story for too long, especially not one as massive as Star Wars. Otherwise, the narrative become bloated, ret-conned, and convoluted. We can see that in Marvel and DC comics, which have been telling the same stories for over fifty years now. And some of the plotlines can get very tired. Case in point, which of the following statements is false:</p>

                <p>A) Spider-man had a bunch of clones running around, each thinking they were the real Peter Parker.</p>

                <p>B) Peter Parker got married to Mary Jane and then un-married by the devil.</p>

                <p>C) Dr. Octopus took over Peter’s body for several issues and acted as an edgier version of the hero.</p>

                <p>D) Green Goblin had kids with Gwen Stacy and sent them to kill Spider-man.</p>

                <p>Trick question, they’re all true. But why am I bringing this up? Because I fear that when the Mandalorian gained popularity, somebody, somewhere realized they needed to milk this story for all it was worth rather than following a clear narrative path with a satisfying ending. As it was, an ending was hinted at, foreshadowed yet…wasn’t executed.</p>

                <p>Star Wars tends to follow familiar story beats. Ideas about destiny, inheritance, and fighting oppression are commonplace. There is a feature that I think, is quintessentially Star Wars. There’s the obvious stuff, inspired by history and classic movies. Duels, a grungy sci-fi setting, dictators, and superweapons. But something that flies under the radar is one of the most ancient methods of appealing to audiences. We saw it in Oedipus Rex, we saw it in Hamlet: Tragedy. In the original trilogy, Luke’s surrogate parents are killed, then his mentors. Anakin is revealed to be evil, then gives his life to redeem himself for his son. While it was a good example of tragedy, the prequels blew the original out of the water. It was a master-class example. We knew the cute whiz kid was going to become a monster. We saw all the signs, yet we knew that this path was inevitable. The qualities that made him such a good person; his love, his empathy, his willingness to endure pain and hardship for everyone else were twisted to make him into Palpatine’s greatest enforcer. That knowledge made the pain and tension more visceral. The Disney Trilogy chose to follow it up with pale imitations of the same tragedies that occurred in the original trilogy, with some character assassinations to help move the plot in the desired direction. As for the current saga, the Mandalorian saga, there was a chance for there to be an interesting plot and a terrible tragedy. One that would have highlighted the honor of Din, the bond that he shared with Grogu, and Grogu’s own path into becoming the next Mandalorian.</p>

                <p><b>Spoilers Ahead!</b></p>

                <p>The Book of Boba starts with the titular Boba Fett growing a conscience after escaping the Sarlaac pit. He decided to stop working for a bunch of rich morons (fair) to become his own boss, taking over Jabba’s territory. Seeking to protect his new territory from the Pyke Syndicate, the galaxy’s biggest spice-runners, he gathers a team both among the locals and old associates, making enemies of certain people at the same time…enemies we don’t see again. He negotiates with local gangs (badly) and refuses to allow spice trade because it would harm his people. Which is oddly upstanding for a guy raised to kill people for profit, as he seems to revel in the locals’ admiration for standing up to them. The toyetic bounty hunter had shifted from a lawful neutral (at best) to the awful lawful good, the type that’s too gullible to consider people betraying him. He enlists the help of Din, a Mandalorian indebted to him that had just been kicked out of his incredibly insular three-person cult (Is it even a cult if there’s three of you left, and you kicked out the third?).</p>

                <p>So, the old, stoic badass-turned-idealist has got an isolated Din, who has just lost his surrogate child and his supportive community, under his wing. While Grogu would have to choose between his past with Din and a future with Luke…who is forcing this choice on him, which seems uncharacteristic, but whatever. What you should be wondering is how two choices could have made this series completely different and set up for a classic tragedy.</p>

                <p>1. Boba Fett is still a heartless man capable of doing what’s necessary to ensure he remains in power.</p>

                <p>2. Grogu, as a child, doesn’t understand the finality of his decision, and chooses the shiny new thing.</p>

                <p>This helps reframe the story, with Boba not as a benevolent ruler, but one that keeps his people in line with kindness to ensure loyalty. He would willingly alienate the gangs and the Pyke Syndicate as they would represent a threat to his ambitions. He aligns himself with capable, like-minded people with no real home, fellow bounty hunters and outcasts. He presents himself as an instrument of change, while holding the same ambitions as other powerful people in the galaxy. He would be like Palpatine, but more experienced in combat than politics. We’d follow him on his journey as he climbs up the ladder, sometimes stumbling but always learning. And beneath him, honor-bound, would be Din. Lost, alone, with the only person that reached out a hand in friendship another disgraced Mandalorian.</p>

                <p>Grogu would learn at Luke’s school. He would make friends among the newer apprentices, but sometimes he would dream, he would look at the stars…and doubt. Time would pass, and we would see the forest around the school become cleared, just as we saw it first being built. And soon, there’s less greenery as more and more darkness takes hold. Nature is replaced by industry, homes, and the original beauty is replaced by conforming town blocks and monochrome unity. A new apprentice joins, idolizing what Grogu and Luke represent. A child named Ben Solo.</p>

                <p>Boba Fett would struggle; he would lose friends and make enemies, he would suffer losses, but eke victories. Until slowly, he would become a major player on Tatooine. A major player who has bad blood with Luke, the man who sent him careening down into the Sarlaac pit all those years ago. A powerful man with a grudge and a Jedi raised on Tatooine trying to recover his people’s legacy. And Grogu, as one of Luke’s first apprentices, would be with him when the two major powers would come into conflict. He’d be forced to fight Din. Lightsaber would meet darksaber as neither would want to hurt the other, but they stand opposed. Luke would beat Boba, one final time. Luke and Boba’s history is more than superficial: it was the Jedi that caused took Boba’s father from him, the Jedi that set him on this path on their quest for peace. It was Boba who delivered Luke his greatest defeat at Cloud City, another faceless helmet that stands opposed to him. Din Djarin would die, but his ideals would live on through Grogu. And Grogu, the first apprentice, would renounce his Jedi teachings and leave with the darksaber to become the titular Mandalorian, the one destined to restore Mandalore. Just as the one to craft the darksaber was a Jedi, one who was a Jedi would reunite Mandalore. This secession from Luke would create an invisible schism within the Jedi school. A schism that Ben Solo would be right in the middle of.</p>

                <p>It seems that the story would have gone in this direction, but the Book of Boba chose to go in a different direction, rather than keep to the cyclical themes initially represented. That’s why Boba’s character seems disjointed, why it feels like Grogu’s return is nearly a deus ex machina, why there were such long shots on the creation if the new Jedi school as it was being constructed. There was a plan there, an idea, the ghost of a tragedy yet born…but it was abandoned. For a Disney ending? To milk the saga more? For those hope that the story can be extended and put on life-support for as long as feasibly possible?</p>

                <p>We’re going to follow this story as it falls into this Spider-man phenomenon…Ridiculous things are going to happen as more and more writers get onboard and compete over the directions the narrative should take, all while nothing really changes. Fans would have to compile lists on what to watch and what to avoid, which continuity we’re on, which alternate world, which alternate Mando or Grogu, or whatever other character that somebody can squeeze more money out of. Newer fans would need to watch more and more material before getting into the franchise’s newest hit, making it exclusionary as more and more material on the same character, the same story, piles up. Points get rehashed, origins retconned, themes lost and rediscovered. It’ll be a mess if there’s no ending, a mess if there’s no plan. People would spend time trying to figure out what the heck is going on, rather than enjoying a good story. I hate to have to say this but being entertained shouldn’t be a job. And if I have to dig through seventeen different issues, series, websites, and books just to know what is going on and satisfy my urge to hear a story, that’s not entertainment. It’s research into a badly curated world, and it’d be a freaking job.</p>

            </Container>
        </>
    );
}

export default BobaFett;