import { Container } from '@mantine/core';

function FlavorsOfFiction() {

    return (
        <>
            <Container>
                <p>Millennia ago, we used stories to explain how the world came to be and why things were the way they were, all while exploring morality. In real life, sometimes the bad guy gets away with injustice. But in stories, we console ourselves with ideas of karmic retribution either with concepts of an afterlife wherein evil is judged and good is rewarded, or tales of heroes overcoming villainy to set things right. It’s therapeutic to know that the jackass that cheated you is going to suffer an ironic punishment in the afterlife. These myths and legends still permeate the public consciousness, although we know them to be nothing more than exaggerated tales of historical figures at best. At worst, they were propagandized stories of so-and-so’s glorious ancestor that existed, I promise, but if you try to look for historical records I will stuff you inside a bronze bull and roast you over an open fire… Nevertheless, stories of dryads and satyrs, of knights and wizards, of good and evil, of gods and men continue to this day not in historical fiction, but within the fantasy genre.</p>

                <p>Perhaps the author that codified the fantasy genre as we know it is Tolkien. Elves, dwarves, and great evil exist within the pseudo-medieval world he’d crafted, living alongside kings, dragons, and the advent of industry. He’d popularized Norse elves and dwarves as the default, rather than the typical mischievous fae that were so common in British folklore. Before Tolkien, fantasy was a loose term for anything involving magic. Conan the Barbarian existed before Lord of the Rings and was popularized with Schwarzenegger’s role. There also exists the settings in which a normal person, usually the audience surrogate, enters a mystical new world on a hero’s journey to find their way back home. See Chronicles of Narnia, Peter Pan, Alice’s Adventures in Wonderland, and the Wizard of Oz. Nowadays, this overt hero’s journey is referred to as an isekai, due to recent popularization of this subgenre in Japanese media. Oddly enough, this subgenre is more closely tied to western fantasy rather than eastern fantasy, which follows story beats similar to that of Journey to the West, the War of Three Kingdoms, and that of self-improvement attributed to Dragon Ball and the wuxia genre.</p>

                <p>Where in the hell did fantasy go between King Arthur and Wizard of Oz? Due to the little hiccup we like to call the Dark Ages and the proliferation of Christian doctrine, there was a hiatus of popular fantasy stories. There was still folklore, but it was a time when if you weren’t writing about Christianity in Europe, you were writing about Classical literature from the good old days of Greek and Roman hegemony. But then comes the Age of Enlightenment, and new ideas start getting written down and kept rather than tossed into a fire with the author. People realize there is a reason amidst the madness that governs the world. Physics, chemistry, biology, and many more fields are explored, understood, and analyzed. The mystery of magic is pushed aside by the wonders of science, and people began waving away mysteries with semi-educated claims about blood transfusions, semiconductors, and quantum-whatever-the-hell-you-want. In the mid-1800’s, a Frenchman with an overactive imagination began to write adventure stories about things that were radical and impossible, like ships that could travel leagues beneath the ocean’s surface, traveling the world in a hot air balloon, and reaching the moon with an explosion-powered rocket off the coast of Florida. Total poppycock. Despite the widespread popularity of his books, Jules Verne was snubbed in literary circles because his works were, in today’s words, ‘too mainstream’. The more things change, the more they stay the same. Verne wouldn’t be the flash in the pan that his critics claimed him to be. Decades later in the castle of a Lord Byron, an eighteen-year-old woman was dared to make a horror novel during a particularly cold summer. Mary Shelley was one of the most influential writers in the world, not only having helped define gothic and horror genres alongside Bram Stoker and Edgar Allen Poe, but built on the ideas of science fiction left from her predecessors. Where Verne espoused the wonders of human engineering with stunning accuracy and started the steampunk subgenre, Shelley explored the moral ramifications and potential pitfalls of science in her classic horror novel, Frankenstein.</p>

                <p>Just as conventional fantasy takes place in a ‘fantastic setting’ in a sort of olden times, there exists fantasy that takes place today, usually in a ‘hidden world’, akin to Percy Jackson, the Dresden Files or Harry Potter, often referred to as urban fantasy. Similarly, there exists fusions between fantasy and sci-fi, wherein magi-tech exists or is developed. Arcane is a notable example of this, trending towards a steampunk era. In contrast, Star Wars is also a sci-fi fantasy, but takes place in a setting with technology on the forefront, with sci-fi concepts such as interstellar travel, droids, clones, and lasers taking the main stage despite ‘canonically’ taking place ‘a long time ago, in a galaxy far, far away’ and the presence of the mystical magic system, the Force. Magic and technology are separate, despite how relevant the plot both are. One of the best examples of sci-fi fantasy is a subgenre of its own that’s dominated theatres for the past decade, the superhero story. In a return to classic myth, larger than life figures have powers beyond mortal reckoning, either by birth on an alien world (Superman and Thor), by magical means (Suicide Squad and Dr. Strange), by accident (Hulk and Spiderman), or by technological innovation, self-study, and a whole lotta money (Iron Man, Black Panther, Batman) to experience hero’s journey and overcome whatever challenges fate has set for them.</p>

                <p>Moving away from fantasy, we delve into fiction that could have happened. This covers a wide array of genres: Romance, mystery, thriller…and if the author writes about something that could have happened in their time, it could be any one of these and more…however, if it delves into historical events, it becomes historical fiction. Shakespeare’s Antony and Cleopatra is one of the best examples of a period drama and historical fiction, and Judson Robert’s Strongbow Saga is one of my favorite revenge stories taking place during the Nordic raids of France. Though to be fair, it is the only revenge story I’ve read that happens the Nordic raids of France…Anyways, there are other forms of exploring what could have happened in fiction. Alternate history tackles questions like what if the Nazis won (The Man in High Castle), what if Nazis won (Wolfenstein), what if the Nazis won (Fatherland), and what if a bunch of white supremacists went back in time to supply the American Confederacy with advanced technology (Guns of the South). The subgenre is a bit repetitive.</p>

                <p>We’ve covered a realistic past. Now a realistic depiction of the future is called a speculative fiction, as in we can see the events in these stories happening. It has less a focus on advanced technology and more on societal changes and challenges. Speculative fiction can fall under several different sub-genres, including but not limited to utopia, dystopia, apocalyptic, and post-apocalyptic. In some cases, one sub-genre could lead into another, as we acknowledge larger, wicked problems could cascade into bigger and bigger consequences. It is a more modern approach to literature, as it strives to encompass global predictions and challenges, rather than the more Western focused narratives. As it should be: I’ve only mentioned a few non-Western stories so far, and I really want to see more.</p>

                <p>Anyways, I’m not trying to get on a soapbox about how we need more ‘realistic and forward-thinking’ stories, nor am I saying you need to categorize our stories. If anything, I want to see stories that break the paradigm, that could fit anywhere and nowhere on the chart I’ve shamelessly stolen and edited to reflect the process of my thoughts. If anything, this is meant for the student struggling to come up with a response as to whatever the hell they’re supposed to be analyzing. To you, the high school student trudging through Jane Eyre because it is considered a classic even though it is so boring you’re willing to scour the internet for any version of CliffsNotes, I wish you good luck and promise that if you bullshit hard enough, you can get an A and fulfill the necessities of your soul-sucking standardized testing.</p>
            </Container>
        </>
    );
}

export default FlavorsOfFiction;