import { Container, Title } from '@mantine/core';

function StoriesProsper() {

    return (
        <>
            <Container>
                <Title className="order3">Or why the Halo franchise never seems to work outside of video games and books.</Title>
                <p>These past few years have shown incredible growth in our media. As movies get larger budgets for greater effects, the studios behind them tend to play it safe. Gone are the days of experimental and wacky. The 80’s were indicative of the willingness to explore new concepts and ideas as special effects became more prominent. It became possible to make better science fiction or fantasy as we mastered computer animation and practical effects. While I reminisce films that my parents watched in their youth to share with me, it’s easy for me to forget that for every E.T., there were at least ten Mac and Me’s.</p>

                <p>We shouldn’t expect companies to prioritize art and quality over guaranteed profit. Which is why the Marvel movies are so important in cinematic history. Not for their quality, but for their ability to make movies from an established medium for an established audience. Furthermore, to make massive movie franchises by relying on so many different characters whom all rely on one another. It’s hard to make a good, original premise of a fourth Indiana Jones. Much easier instead to switch to another character in this established universe and give them a chance to be the protagonist. And if the bonus is that there are already people invested in the character before the movie even comes out? Those are guaranteed seats filled. But movies have existed for over a century, and comics for even longer than that. Why did it take so long for the formula to work?</p>

                <p>Earlier live-action superhero movies failed due to a variety of factors. For one, US audiences view animation as a ‘children’s medium’, which has only begun to change in recent years as animated movies and series from overseas have become more accepted. Nevertheless, some stigma persists, and animation is expensive.</p>

                <p>Secondly, it’s hard to translate the design of a comic book character into real life. Look at the old Hulk and Captain America movies. X-men sidestepped this issue by lampshading the ‘silly costume’ designs in an off-handed comment about yellow spandex, all while donning more ‘utilitarian’ uniforms. And while the trilogy was okay, it wasn’t the suits that made it interesting. Rather, it was the incredible performances by Ian McKellen, Patrick Stewart, and Hugh Jackman that dominated the silver screen, encapsulating the characters they played brilliantly. It proved that it wasn’t the costumes that made the characters interesting (duh).</p>

                <p>Finally, the biggest issue faced would be the twin-headed dragon that is audience expectations and source material. These two facets are intertwined: the source material acts as a sort of baseline from which an audience can form their expectations. Deviate from that baseline too much, and the audience will feel lied to. This is the trickiest part, as it has a lot of moving parts. You can’t cram too much of the source material into a movie, as it would become bloated and not allow for proper pacing, setting, character development, et cetera. Too many cooks can apply; if you stuff too many villains with half-baked motivations or side plots to up the stakes for the hero, they become less than the sum of their parts. We saw this in Batman & Robin, and Spiderman 3 as multiple narrative threads enmeshed themselves in the same sort of mess one might find their earbuds after five minutes in one’s pocket. There wasn’t enough time to properly address everything, so they came out half-baked.</p>

                <p>If there’s too little source material, it can become rushed or seem disingenuous. This is more difficult to avoid, as anybody who wants to put a new, creative twist on an existing character or concept can cause a rejective reaction in the audience. The example that comes to mind would be Iron Man 3’s Mandarin. In the comics, the Mandarin is more than an antagonist. He is a dark mirror to Tony Stark in every way. Born in poverty, he chose to conquer using the power from mysterious alien rings as Tony inherited his wealth. He mastered his body as Tony mastered his mind. When he sought to understand more about his rings, he captured Tony Stark, who only escaped by making the first Iron Man suit. Already, this archnemesis’ fate is tied to Tony’s. But in the movies, the Mandarin was just another guy. Sure, they tried to give him a (really bad) backstory about how Tony slighted him. But rather than have incredibly powerful rings of alien origin, the Mandarin (now Killian) had a weird chemical procedure that makes him a hot (literally and figuratively for some reason) super-soldier. Conveniently ignoring the ramifications of the super-soldier procedure in the MCU. Then Pepper kills him. There was no catharsis in his interactions with Tony, just a series of misdirects aimed at tricking the audience with little to no foreshadowing. The result was trying to fit a square peg in a circular hole. Killian was supposed to be the Mandarin, but he was so out of place, even casual Marvel fans felt cheated. A potentially awesome character was thrown aside and forgotten, when he was as much a part of Iron Man as Loki was to Thor.</p>

                <p>As for an example of a movie adaptation of a franchise that fails both the source materials and audience expectations, I want you to briefly think about the Avatar: The Last Airbender movie. They mispronounced the names, got the characters wrong, and stuffed a season’s worth of story, character development, and world-building into a single movie. Now forget about the atrocity once more.</p>

                <p>Compare it to The Batman (2022), which is incredibly long. But it addresses the motivations of the villains, the stakes, the setting, and the characters so aptly that the narrative threads entwine to form a stronger narrative ‘cord’. All while leaving the narrative threads open for further development. With the amount of times Batman has been made for the big screen, you’d think it to be Shakespeare.</p>

                <p>How does this all relate to Halo as a franchise? Halo fans know that the video game series has made many attempts to break into theatres or shows. What they fail to realize is that it took a long while for proper comic adaptations to be made. And as movie-making executives funnel more money into reliable projects, it is natural they would set their sights on popular series with established fandoms. Every now and then, they try to make a movie adaptation of a video game, only to fail spectacularly. There was a Super Mario movie, there were Mortal Kombat movies, and there were Resident Evil movies. Most movies inspired by video games often are horror themed, which may account for their failures considering the low success rate of horror movies in general. Recently, VG-inspired movies have been getting better. Still not incredible, but we can’t deny the quality has gone up somewhat.</p>

                <p>The main hurdles to make these movies is like that of comics: design, audience expectations, and source material. However, the nature of these hurdles is different. Design is no longer influenced just by artists and super-suits, but also the limitations within the game at the time. The source material is mostly the environment a player finds themselves in rather than the character they play as. Most video games have a protagonist that meshes well with the player. Silent or laconic protagonists allow for better player immersion but make it difficult to like as movie characters, and harder to understand when you can’t exactly play as them. This is doubly difficult as an audience that has played as the character has different expectations than one who observes the character. There’s already a wide disconnect between player and viewer, further widened by the fact that different players have different experiences. That makes satisfying audience expectations nearly impossible. Finally, the source material is difficult to properly encapsulate; a show or movie needs to start in a place and time where we can discover as much as possible without it becoming an exposition dump, to satisfy both newcomers and old players. Which I will give the Halo series on Paramount+ a pass on, since they managed to start from an interesting location without bombarding us with too much.</p>

                <p>The issue I see with the Halo series is not with the design, but rather the execution of the source materials to try and satisfy every possible audience. This is a bad move, as it becomes too generic or played out. Spoilers ahead, I guess. In the first episode, we are introduced to the audience stand-in, who tried to get high from spaceship fuel but found alien forces that start to chase her. She manages to escape pursuing aliens by hiding back in her camp. An insurrectionist camp that is right in the middle of an open field and visible from orbit by the way. The Covenant weaponry is incredibly lore accurate, and how they indulge in their zealous genocide of the insurrectionists fits as well. For now. It is only when the Spartans come in to kick their ass that things move from slightly cheesy (which doesn’t really fit with the tone) to ridiculous to the point you’d think we were watching UNSC propaganda. Over a hundred guns concentrating fire on Elite aliens slowly walking through smoke does nothing, but a few shots and punches from a Spartan can decimate them. Maybe if we saw any Elites die to the hail of gunfire only to overcome superior numbers through better tech (like their invisibility, or Banshees and Ghosts, or plasma grenades) rather than just running in like a bunch of brutes. Or show how normal humans can’t properly use the higher caliber weapons Spartans can use. Maybe show the Spartans being capable of more than big jumps and gun-fu, like being able to destroy shields better due to their inhuman accuracy or using actual tactics. However, they do properly emphasize how inhuman Spartans are, empathetically, when the audience stand-in cries over her dead father as Master Chief and Silver Team walk away from the slaughter to find the Covenant drop site.</p>

                <p>Everything I’ve just gone over could have happened in the Halo games. As with Spartan-117’s team, some things have changed. This comes back to source material, as the amount of lore that has been developed and ret-conned since the first game is so much that the showrunners tried to correct some of the glaring issues. For example, if the Forerunners were so prevalent that their artifacts are found practically everywhere in the later games, why haven’t humans been affected as reclaimers more often? The reason for the Covenant genocide of humanity is because their leaders claimed human existence as heresy, since Forerunner artifacts reacted to them, invalidating the entire religion. It stands to reason humans are more likely to be recognized as reclaimers and affected by either the artifacts themselves or different factions of the Covenant in different ways. In the first episode, there are two examples: a human that is revered by the Covenant, and the Demon of the Covenant, John-117. Master Chief finds one of these artifacts and it starts undoing his UNSC ‘programming’, which leads to him becoming irrational and not following orders as he protects the audience stand-in from UNSC’s usual ‘silence the witnesses’ shenanigans.</p>

                <p>It became too strange to watch after that. This was not the Master Chief I knew, nor the Spartan awesomeness I was accustomed to. This was a story that required forced contrivances to make MC relatable rather than working around his stoic, faceless exterior and through how he reacted to the impossible odds stacked against him made him super, yet human. The little bits, the chinks in his armor that we’d see every now and then. Instead, the helmet comes off in the first episode to appeal to our humanity without even getting a chance to know him slowly. In attempting to subvert audience expectations and work with the source material, showrunners have used the basic skeleton behind the Halo series and added things that run against the most basic source material to have an easier time in characterization and storytelling. The story isn’t ruined, but it can’t compare to the original story and suffers because of it. I suppose that’s what happened with District 9, which was supposed to be a Halo movie.</p>

                <p>All in all, franchises are comprised of stories that are meant for specific mediums. Writing a story meant for a comic book will be better as a comic, and writing stories meant for a video game will work best as a video game. Not even books are free from this rule. To adapt a story to another medium means to accept the strengths and weaknesses of the medium it came from and the one it will come to occupy. Like an organism, it must be properly adapted to survive in this niche, and any multi-media writer should be aware that some things translate better than others.</p>

            </Container>
        </>
    );
}

export default StoriesProsper;