import { Container } from '@mantine/core';

function SpaceBetween() {

    return (
        <>
            <Container>
                <p>Corona demarcated flaws in our society and will have lasting consequences for all who experienced it. There will be health and socio-economic issues that will be discussed for decades because of what the virus has unearthed. For introverts and social recluses, this period has been one of a deep isolation, a type of separation hitherto unseen in the past century. Some may enjoy the seclusion. Others, like me, have felt an existing valley widen between people that made social connections an even bigger hurdle.</p>

                <p>When I was young, I couldn’t get too close to my friends. They seemed caught up on ideas of ‘personal space’ that existed between people, a concept I had to adopt to be accepted as ‘normal’. This space that exists to separate people, akin to that of squares on a tabletop game map, made it hard for me to connect with people. I am a tactile person; I may see the world with my eyes, or hear it with my ears, but I experience with the entirety of myself. When I swim, my lungs burn as I dive, my muscles straining to pull me through the all-encompassing embrace of the water. When I wake, theses sensations overwhelm me in the light of dawn, the sheets flittering across my fingers and drawing down from my sensitive lips, as the fuzzy somnambulance leaves me in a state of feeling the barest whispers on my skin, sending jolts of pleasure across my body. When I walk, the wind dances in my hair, falling leaves caress my face as they drift pass me, and errant drops dapple across me in a kaleidoscope of feeling. When I meet people, I want to hold their hands a bit longer as we shake to soak in their warmth, I want to clasp them in a brotherly embrace to feel their whole self and let them feel my whole self, so we can understand one another.</p>

                <p>But normal people don’t need to be touching to understand each other. They can get by on the subtle facial expressions, the stressing of tones in their voice. And here I am, alone in an ocean of personal bubbles. I grew up, used to that, interspersed by truly touching moments with family and close friends. I had connected with various cliques in school, and then in college, but it was always distant. We talked, we laughed, but I could never be myself for fear of isolation. I was content with a facsimile of a relationship with my peers, fearing its loss in my search for the real thing.</p>

                <p>Space isolates and terrifies me. Every aspect of it scares me. From open fields and large buildings that expand my perception, to the various cosmic phenomena that occur on a scale that send me spiraling into an archaic fear, the fear of one who understands our significance and the finality of death for the first time. I remember looking up at a tall building in downtown Miami as a child and felt as if I was being stretched taut, like a balloon just before it would pop. I would stay under cover of trees and overhangs because of some irrational fear that gravity would cease to be and I’d be flung out in the far reaches of space.</p>

                <p>I am an ape staring into the abyss it wasn’t meant to understand. I’d re-emerge from the event horizon of sleep with adrenalin pumping through my veins and run in a blind terror, wailing and blubbering uncomprehendingly. These sensations were born from errant thoughts regarding supernovas, black holes, galactic collisions, heat death, and the yawning void that exist beyond human comprehension. And I’d feel incredibly alone. The first thing I would do is run towards the closest person — my parents when I lived with them, then roommates for a short time — and just hope to talk, to not be alone in my madness. It’s gotten better in recent years. No longer do these thoughts occupy my mind. Things have gotten worse in different ways, though. Now I distract myself with the bookends of my day; doom-scrolling through social media after I wake up and before I go to sleep. I read about children dead in Afghanistan, people starving in southeast Asia, earthquakes in Haiti, and injustice everywhere. More on the forefront would be the virus. The politicization, the side effects, the rising number of infected, of deniers, of dead. My mind struggles to find solutions for people with no connection to me save for a few pixels on a screen, and my bones ache with discomfort at all that I cannot do. Do they too, feel alone in their struggles that make mine look miniscule in comparison, that make me hate myself in my self-pity? Ironic that the people furthest from me can touch me most acutely. Ironic that the passerby on streets, fellow neighbors and countrymen, are stranger to me than any other, despite how we share the streets, the air, and local burdens. With them gone, the ocean of personal bubbles turns into a vast desert, an empty space of what should be.</p>

                <p>I was made aware of this desert once again after I left home by bike in the early morning. I’d strapped my helmet, checked my pockets, and loaded my bag on the gravel outside my home. A few unsteady steps atop my bike turned into a practiced motion, legs burning as they pumped up and down on the higher gears. I kept to the backroads, conscious of every vigorous root digging beneath the sidewalk. As I moved from one neighborhood to the next, stray cats casually walking across empty streets were replaced by flocks of preening peacocks. A male was showing off his plumage to a hen in the middle of the road beeping angrily at me as I passed. I wiped the sweat from my brow as I crossed the small bridge and saw the first person since I began to ride ten minutes prior. The first early bird. I waved at them awkwardly, and saw a few shadowy fingers raise up in acknowledgment, the rare bit of interaction I’d received for the week.</p>

                <p>I didn’t see anybody else walking, or riding, or driving, after I passed a larger round-about and began riding on one of the busier streets. Normalcy returned as the busy people began waking up to get to work. A scant few people getting into their cars as the sun began to peek over the horizon, rays reaching across the sky in a morning stretch. My lungs strained as I stood up on my bike and pedaled faster. I needed to get there before the morning rush. Rivulets of sweat ran like rivers down my neck, merging into an uncomfortable sea of sweat between by bag and I. Almost slipping my bike on a turn covered by rotten fruits and wet leaves, I pumped harder and harder to escape the tidal wave of people that would surge. The liminal space of morning began to populate into activity once more as Miami woke.</p>

                <p>I made it into Matheson and Hammock Park as cars began polluting the streets, the morning smell of vegetation and exhaust quickly replaced by the dankness of mangroves and brine. I stopped pedaling as I streamed through a particularly large puddle, letting the water spray across my shins. I lay my bike down in the grass and take a deep breath as the morning light cascades across pink clouds on the horizon. The expanse ahead may have once scared me, but it now brought me a type of comfort. I leaned back against a palm tree, sand clinging to my sweaty palms and trickling off me in tiny landslides. Thoughts breached from my unconscious mind, an errant memory of other liminal spaces I’ve experienced.</p>

                <p>The strip mall without any cars in the parking lot, an empty place with boarded windows, empty storefronts, summoning some ancient fear within an empty mind. There should be people there. A place that was teeming with activity, devoid of movement. Not even the wind dared move in this bloated corpse of commerce. The cold metal of the locked door handle stuck to my skin in a sympathetic desperation to keep my touch, my warmth.</p>

                <p>The pedestrian mixed neighborhood in Iowa City, still wet from the freshly melted snow as burgeoning greenery came back to life. Noise dared not appear here, the sun could not bear to peek through the clouds to look upon the emptiness. The bricks were uneven beneath my feet, the frigid air seeking refuge within any available orifice, swarming my eyes, my nostrils, freezing me within and out. My mouth clasped in a grimace that nobody would see, shut behind the mask that had slipped from my nose. There were no smells of baking bread, burgers, grilled cheese, coffee, just a sort of sad humidity. My favorite little eatery had blacked out windows, my sad reflection the only other person there.</p>

                <p>The airport as I left Iowa, the lights above humming and the sound of my luggage rolling echoing across empty halls. There were no lines, no waiting, there should have been no anxiety. And yet the emptiness tickled by brain’s panic centers, as if the throngs of people that made me uncomfortable, and the bustling of luggage, and the weaving between slow walkers and loud talkers, as if it was all preferable to the emptiness that pervaded this small airport. My lizard brain would not accept it, it screamed out to me that there was a predator nearby, there was a reason it was empty. The rational part of my brain knew that to be true; a virus I had yet to be inoculated against had plagued us in our minds and our bodies. I was wary, but I wanted to go home. I was done studying, and I had no opportunities for jobs. I couldn’t afford to stay. I needed to go home. And yet I still felt guilty. I celebrated my birthday with my roommate, I wore a mask everywhere, but I still felt equal parts guilt and rage. Rage at myself for being like those partying during a pandemic, by simply being outside. Worse yet, I was leaving the friends I’d made in college behind. I had finally gotten my degree, but I was going to be alone. Again. Physical friends reduced to online contacts I would likely never meet in person. The space between myself and those like me had broadened, as it had become filled with the lackadaisical and arrogant strangers.</p>

                <p>When I wrote, I managed to touch people. But they could only barely touch me with their comments, their praises, their likes, as I felt like they were meant for another, more capable writer. I wondered about that, as the sun rose high on that small beach in Miami. I felt close to the people I followed online: comedians, artists, animators, writers, and scientists. But to them, I was words on a screen, a random username lost among a crowd. Do they feel the same? Or do they believe them to be closer to their audience? Inversely, does the audience believe to have a personal connection to these people online, successful people they’ve never met aside from a response to a Twitter post, or a like on Facebook at a witty comment?</p>

                <p>Space and touch. I mused on the concepts as I took a swig from my bottle, water droplets escaping and trickling down my chin. I wanted to feel, to be touched, to connect. But there are gulfs that exist between people. Borders that separate things that do not appear distant. Between people, between ideas, between feelings. The space that separates a person from their ideal. Or the space that separates me from a car on the street, a simple line on the pavement. I biked in the heat as I thought this, taking refuge from the baleful sunlight in the dappled groves, careful to avoid the dangerous drivers of Miami. The humidity clung to me, suffocating every pore, draining me. It was almost as if I was struggling to breathe in water, with neither the refreshing currents and casual grace of the ocean, nor the carefully maintained crispness of pool water. It clasped onto my throat and tightened without respite, almost as merciless as my own self-destructive thoughts. I got home safely, appreciating the sight of sunbathing lizards on concrete driveways and tin roofs. I felt a bit jealous of those reptiles basking contently in the sunlight but laughed nonetheless at the sight of them as they licked their own eyes.</p>

                <p>I put away my bike and got lost in thought as I dream in a haze of post-exercise bliss. I imagine a better me, more confident and less doughy. He’s a guy who takes praise with humility yet accepts it as someone’s truth. He can carry a conversation without relying on self-deprecating humor. He doesn’t need to be successful at everything, but people feel better upon meeting him, and he finds himself content meeting new people, without ever getting tired in social situations. Not just that, but he actively makes the world a better place. He has a fulfilling job that allows him to subsist while convincing people to make sustainable choices, and a close-knit group of friends that he can regularly interact with, without ever feeling like he’s bothering them. The space between the me that exists and the me that would do that is larger than any space that gave me my waking nightmares.</p>

                <p>In a world that allows us to connect with so many others in the blink of an eye, where impressions are reduced to a set number of characters and algorithmic chance, the ideas are more real than the people. And I feel small. I feel alone in a void of indifference. A new type of space has come to haunt me, the type of space that separates people, one called solitude.</p>

            </Container>
        </>
    );
}

export default SpaceBetween;