import { Container, Title } from '@mantine/core';

function SustainableMiami() {

    return (
        <>
            <Container>
                <p>Trying to live for a better tomorrow is harder than ever. Previous generations didn’t worry overmuch about witnessing the negative consequences of rampant industrialization, seeing the benefits it provided them. Nowadays, we begin to pay the price with a more hostile climate and an unsure future. It is no longer the fear of a nuclear winter, born from an ego contest between superpowers that threatens our existence, but the complicated series of systems bringing about a slow and seemingly insurmountable change. You can’t vote out or protest climate change; the dice have already been cast. It is no surprise many would choose to bury their heads in the sand and deny reality. But history has proven time and again: humanity will survive once we come together and adapt. The solutions are as various as the cultures and climates we inhabit. I’ve decided to compile a series of strategies that Miami locals can adopt to help build a future for the generations that follow us. These are just a few ways we, as individuals, can help preserve our ways of life.</p>

                <Title className="order2">Active Transportation</Title>

                <p>Active transportation is any form of transportation that relies on human energy to use. Walking, biking, those weird horizontal pedal machines, they all rely on our own strength to move about. Even though it’d be tough to bike anywhere at first glance, we have the best conditions to become the most bikeable city in America rather than eighth. That’s right, even with US-1, all those busy roads and bumper-to-bumper traffic, Miami is the eighth most bikeable city in the country, mostly in part due to the amount of money poured into biking initiatives.</p>

                <p>It makes sense when you think about it. Miami is flat. Our highest point is in Coconut grove, a mere 24 feet above sea level. If you’re a local, you probably didn’t even know that because it’s so gradual. The very thing that makes us so vulnerable to climate change makes it easy to combat it on a local level. Furthermore, South Florida has one of the best climates for biking. It’s tough to bike in high heat, but I guarantee you it’s close to impossible in any type of snow. Take from the guy who couldn’t even walk uphill in a wintertime Montreal because of the ice. Miami is one of the best places to get around under your own strength. Places like Miami Beach, Key Biscayne, and Coconut Grove are so easy to walk around in, not just because it’s comfortable, but because there’s local stores everywhere. And people know this. Look at how many bikes can be rented, or the availability of rent-a-scooters.</p>

                <p>There is a myriad of benefits to active transportation. For one, it’s healthy (obviously). It also reduces your carbon footprint — Yes, even if you have an electric car. As of 2015, over 60% of Florida’s energy comes from natural gas, which is marginally better for the environment compared to oil or coal, but still. There’s also the fact that a lot of people rely on their cars to drive a large distance to work, to places that are unreliable to reach with our lackluster public transportation system. Relying on active transportation to get somewhere frees up roads for those that desperately need a car.</p>

                <p>Someone reading this is probably telling themselves “I can’t possibly bike somewhere/ walk that far/ see myself in one of those ridiculous horizontal pedal things!” To that I say, you’d be surprised at what you can do. If you worry about the younger ones of your family getting tired, they have a lot more energy than you think and you aren’t limited to conventional bikes: there are four-wheeled bikes to take your family on adventures. If you can’t see yourself getting to work in a sweat, see if your boss is okay with installing a work shower. If you live too far away from anything, that’s okay. Don’t feel guilty about needing to drive. There are other ways you can help.</p>

                <Title className="order2">Gardening</Title>

                <p>Let me paint you a picture: after years of hard work, penny-pinching, and a substantial amount of luck, you manage to buy your own home before some company does for the express purpose of renting it out. It’s got a picket fence, a nice driveway, three (!) bedrooms, and a beautiful green lawn. Why does that sound so great? Why are we so happy with what’s basically a stereotype? Is it because we’ve associated this image with success? Chances are, if you own a home with enough room for a lawn, you’ve got one. For some reason it’s how we can see if somebody has ‘made it’ in life. It’s a status symbol that we bought into when we saw rich people with massive yards and lush green grass, who themselves have it because it was an old symbol of European aristocracy, all because castles had the trees cleared around them to see enemies coming.</p>

                <p>Last I checked, we don’t exactly have ramparts with arrow slits and divots to pour boiling water down…so why maintain effort in a lawn? You have to mow the lawn and rake leaves if you don’t want it to look messy, treat it with pesticides so bugs don’t make it their home, and use special fertilizer so it looks nice and green. At this point, I don’t care how tacky fake grass is, it just seems objectively better. After all, not only does it require less work, but there won’t be any fertilizers that leak into our waterways to create hypoxic zones in our estuaries, or pesticides that kill necessary pollinators, nor even the gas used to mow your lawn every week.</p>

                <p>There’s an alternative. Forget typical lawns, leave them in Europe. This is Miami! Let’s be exotic! This subtropical climate means you can grow so many things here. You want colors? We got colors! Blazing Star is a nice purple that attracts pollinators, Columbine flowers look like beautiful red and yellow swans that attract hummingbirds, passion flowers are weird and enchanting flowers that look like some sort of alien starfish. Azaleas are beautiful shrubs that blossoming in throes of pink, ferns cover ground easily in a lush green, palm trees provide fantastic shade and tropical aesthetic. Not to mention all the fruit trees you can grow here. Mangos, avocados, carambolas, bananas, lychees, and dragon fruit…look, my point is, we’ve been limiting ourselves to bland lawns when we could have been growing our own beautiful landscapes and food. All because we were sold this idea on what a ‘successful’ home looks like.</p>

                <p>Like many people, you may not have the space, time, or capital for a garden, but you do have a passion for gardening. That doesn’t mean it’s impossible. There are community gardens scattered across Miami, and they will appreciate any and all help. It might even be a fun family activity! If there’s none nearby, you can always present this idea to local community leaders, like a church, homeowners association, or local council.</p>

                <Title className="order2">Un-Waste</Title>

                <p>We’ve all been told to clean our plate, to recycle, to pick up after ourselves. On an intrinsic level, messiness is negatively associated. Cleanliness is close to godliness. So why are we okay with leaving behind messes? We can all agree litter is bad, but so long as the litter is out of sight, we’re okay with it. When we throw something in the trash, it goes ‘away’. Thankfully, Miami is forward-thinking when it comes to our trash. The Miami-Dade department of Solid Waste takes our trash to separate and process it to burn or recycle. Greenhouse gas production aside, it’s better than dumping everything in a landfill and forgetting about it. Or worse, exporting it to a country with poor waste management. Yes, we actually export our trash to make it somebody else’s problem. Not cool, America.</p>

                <p>But for now, we’re talking about Miami. Thankfully, we have good infrastructure that makes recycling easier. We have trash bins, recycling bins, and leaf piles. However, there are a few things we can’t simply throw away. Liquid waste like chemicals and cleaners, e-waste like old lithium batteries and broken phones…and then there’s the things that take up space. Intact, yet outgrown. Children’s playsets you remember enjoying in your early youth, clothes that no longer fit, books you’ve read cover to cover. Living means using things, but it also means properly disposing of those things. It may be obvious to some, but I’ll lay out some strategies.</p>

                <p>When it comes to e-waste, there are a bunch of private collection services in Miami that will take your older devices, and even clear them for you. These electronic recycling centers are peppered around Miami, but I feel as though it should be a government responsibility.</p>

                <p>For the more toxic liquid waste, I recommend the Clean Management Environmental Group. They have the resources necessary to remove any sort of waste, though they are not a free service. I wish it weren’t so, but safety comes first.</p>

                <p>As for the things you can no longer personally use, Goodwill, libraries, and other facilities will appreciate any forms of donations. Just remember to clean it before donating!</p>

                <p>These are all potential solutions, but the best route is not based on your average person, but on the system of consumption itself. We should be encouraging products that rely on a cradle-to-cradle system, rather than the cradle-to-grave system we have now. Cradle-to-cradle is a system by which a product is made, used, collected, and broken down to be remade again in a cycle. What we have now is the start of such a process, but many products we use are single-use and disposed of. Disposable plastic containers, bags, cups, and straws, wiring that we replace once broken, and other such things with a limited lifespan, when we should be using things that can be broken down and used again at the very least. Which brings me to my next point.</p>

                <p>Choose, don’t consume</p>

                <p>It’s easy to simply buy what you see right in front of you rather than looking around for what you need. With the advent of delivery services like Amazon, shopping has become easier on us…so easy, we don’t look as close as we should. We should strive to be responsible consumers; we vote with our wallets, after all. How can we make sure we vote for a sustainable society using our wallets? Ideally, by using them as little as possible, but that’s not feasible for those of us who aren’t wilderness survival experts (though we could learn a thing or two about wanting less stuff). What all of us can do is make sure to buy as locally as possible. The more local a chain of production the better. These products don’t have to be carried as far, use as many preservatives, and/or use as much packaging as products that are made across the world. Buying bulk packages follows the same idea: it takes less resources to move one big bag than ten small bags.</p>

                <p>As much as I love meat, I have to admit that delicious beef is quite bad for the environment. Around 200 gallons of water are required to make one pound of beef, and about 20 pounds of feed per pound. Now think about how many burgers are sold yearly. Not to mention the amount of methane livestock produces and you’ve got a very expensive meal. I’m not saying we should give up on eating livestock; rice produces a sizable amount of methane as well. I’m saying that we should simply not make burgers the ‘basic’ American meal, we should work to eat less red meat in general. I was staunchly against fake meats for years until I tried some BeyondMeat, Incogmeato, and even a few Impossible Burgers. I can honestly confirm they were all delicious.</p>

                <p>You may be tempted by products promising to be green, good for the environment, organic, et cetera…but the sole objective of a product is to be sold, and many companies will lie about the ‘greenness’ of their product to achieve that goal. This is called greenwashing. It takes a bit of work, but through research and sites like http://www.free2work.org/ we can find these supply chains, and make our discontent known. A reliable method of getting sustainable products is shopping second-hand, which extends the life of a product. And if you have the time or money to repair something, it would best to do so. DIY products promote the most local and trustworthy brand possible: homemade. If you can make treasure from what others consider trash, you’re already in the best mindset for living sustainably.</p>

                <p>Some companies to avoid would be: Nestle for child slavery (I wish I was kidding) and a litany of other, slightly less heinous practices. Tyson for labor rights abuses and mishandling of meat across the globe. Publix and Wendy’s refuse to join the Fair Food Program, which was born from a desire to prevent sexual exploitation, labor abuse, and human trafficking of farmers in Florida. Coors has an extensive history of labor violations, pollution, and funneling money into astroturfing. Note that big companies are more susceptible to this corruption. You may be wondering what this has to do with sustainability, but you have to understand sustainability is about balancing people, economics, and environment. Worker’s rights are human rights, and human rights make society more sustainable.</p>

                <p>The way our economy is set up, this advice can be applied throughout the US, and is more loosie-goosie. Companies change all the time to fulfill consumer expectations, we just need to hold the bigger companies responsible through boycotts and promotion of good products. Remember to do your research, so that we can all discover the best way for these economic juggernauts to properly use their resources.</p>

                <Title className="order2">Resource Usage</Title>

                <p>Planet Earth is a nearly closed system. The only thing that comes in is sunlight and the occasional meteorite. Until recently, the only thing leaving was the minute amounts of light reflected by cloud cover and ice. Suffice to say, no matter how big our planet is, what we have at any given moment is limited. As I am writing this, there are 332 million Americans, and just under 7.8 billion people on Earth. Americans constitute less than 5% of the global population but requires 16% of the world’s produced energy. That’s about 2.3 gallons of gas per person, every day. It’s true that we’ve gotten better recently, and we’ve made large strides in reducing our energy use. Cars and computers have become more efficient, people have gotten smarter in their choices, and we’ve made progress on adopting cleaner energy sources. But these are big issues, too big for any individual. So, let’s get back down to what individuals can do.</p>

                <p>Reducing petroleum use in south Florida is one of the easier things to do. As mentioned above, active transportation is always a possibility. But electric vehicles (EVs), like Tesla cars, are accessible in Miami, and in most other metropolitan areas. Carpooling is also a great solution, as it reduces the number of cars on the road, so less traffic for everyone. Similarly, there’s our diesel-run public transport buses, and although our metro system is pitiful at best, it still doesn’t run on oil. That’s because Miami’s power is mostly born from natural gas, with a significant portion being based on solar power. Considering we’re called the Sunshine State, I think we can do better and make solar energy power the majority contributor rather than the 30% estimated by FPL…maybe even get wind farms off the coast that can simultaneously act as artificial reefs…or refurbish Turkey Point with far more efficient tech and move into better nuclear power… Getting off track, sorry. What we as individuals can do is install solar panels atop our homes. If there’s enough sunlight, we could even sell energy back into the grid.</p>

                <p>Otherwise, we’re pretty set in Miami. Problems like water aren’t crucial, but they eventually may be. That could be assisted by using gray water systems, which reuses water that we use for cleaning in other aspects. For example, the water you used to shower gets stored and used when you decide to water your garden, flush your toilet, or heating. Heck, if you’re industrious, you can even install a water barrel and take advantage of our tropical rains to get your own water supply. We can also look to Phoenix, Arizona as an example of what not to do. Green lawns everywhere, making snow and spreading it in a park to simulate snowy days up north, and just lackadaisical water management in a desert. I wish I was kidding. But this circles back in part to gardening. You don’t need to waste water or spend too much time on a garden that is comfortable in your natural climate.</p>

                <Title className="order2">Community</Title>

                <p>There is a common thread in all the strategies listed above. ‘If.’ If you have time, if you have money, if you have sway, if, if, if. We like to believe others, who have more than we do, can better the world with a wave of their hand. We have to worry about ourselves first, it’s only natural. If we can’t feed ourselves, clothe ourselves, shelter ourselves, how can we be happy? How can we work to better the world? The guilt of trying to simply survive eats at us, when we know that we can’t help. Or worse, we recognize the things we do as bad, but we are forced to do it. Maybe all you have is a gas-guzzling junker car and Miami’s public transport is unreliable for your job. Maybe you can’t afford a meal that’s better for you, or the environment, or even people working in the chain. Maybe you live in a small apartment with two windows, and you can’t grow anything despite wanting to. Chances are, you think you don’t have the money, or the time, or the influence. I want to tell you, no matter what, you have something. You are a person. You have value that cannot be defined by what you bring to the economy. And that gives you merit. It gives you the right. It is through humanity’s greatest strength that we built the systems that exist today, and it is that strength that will allow us to change them to benefit us all. Human unity through our communities, to intermingle our identities and strengths and join as one for a singular, great purpose. Maybe you don’t have much space or time to garden…but there are others who have a little bit too, and you can each bring something to build a whole. Maybe you feel bad about your junker car…but a friend will appreciate when you carpool with them. Maybe you feel hopeless because you feel like you have no power in this vast world to change it for the better. You aren’t alone. You need only look for a community and you’ll find one. Whether it be at your church, the people you play online with, at your workplace, whatever! Together, you can help make little changes, that will snowball into bigger ones. That’s your strength. Your right.</p>

                <p>You never had to fight for the air you breathe, nor the blood in your veins: why should you accept to fight for the things that keep you alive. The second you were born, the right to cry, to smile, to laugh, to live and be happy were yours. It is your birthright, the birthright of all those who came before and all who will come after you. The path to sustainability is one paved with the goodness and understanding of every human being. Environmental problems are social problems, social problems are economic problems, and economic problems are environmental problems. Working to solve these issues together will be what sets us on the path to happiness.</p>

                <Title className="order2">Works Cited</Title>
                <a href="https://www.baynews9.com/fl/tampa/news/2021/06/29/florida-tops-in-southeast-in-solar-power-production-">Florida tops in Southeast in solar power production (baynews9.com)</a>

                <a href="https://www.nytimes.com/2019/07/07/business/energy-environment/florida-solar-power.html">Florida’s Utilities Keep Homeowners From Making the Most of Solar Power — The New York Times (nytimes.com)</a>

                <a href="https://www.eia.gov/energyexplained/us-energy-facts/">U.S. energy facts explained — consumption and production — U.S. Energy Information Administration (EIA)</a>

                <a href="https://css.umich.edu/factsheets/us-energy-system-factsheet">U.S. Energy System Factsheet | Center for Sustainable Systems (umich.edu)</a>

                <a href="https://www.solarunitedneighbors.org/news/dont-be-fooled-by-utility-owned-solar/">Don’t be fooled by FPL’s fake community solar — Solar United Neighbors</a>

                <a href="https://sustainabledish.com/much-feed-take-produce-pound-beef/">How Much Feed Does it Take To Produce a Pound of Beef? (sustainabledish.com)</a>

                <a href="https://www.huffpost.com/entry/nestle-admits-to-using-slave-labor-groups-hope-other-companies-will-come-forward_n_5655cec6e4b08e945fea9729">Nestle Admits To Slave Labor, May Prompt Other Companies To Come Clean | HuffPost Impact</a>

                <a href="https://www.pbs.org/newshour/politics/supreme-court-backs-nestle-cargill-in-child-slave-labor-suit">Supreme Court backs Nestle, Cargill in child slave labor suit | PBS NewsHour</a>

                <a href="https://foodrevolution.org/blog/food-and-health/tyson-foods-industrial-food-imapct-people-animals-environment/?utm_campaign=frn16&utm_medium=email&utm_source=email-automated&utm_content=2327&utm_term=existing-email-list&email=theresponsibleconsumer1%40gmail.com&firstname=theresponsibleconsumer&lastname=">How Tyson’s Cheap Food Negatively Impacts People, Animals, and the Planet — Food Revolution Network</a>

                <a href="https://infolific.com/money-management/4-ways-to-be-a-more-responsible-consumer/">4 Ways to be a More Responsible Consumer | Infolific</a>

                <a href="https://www.freedomunited.org/our-impact/wendys-fair-food-program/">Wendy’s and the Fair Food Program — FreedomUnited.org</a>

                <p>https://blog.ucsusa.org/john-rogers/where-florida-electricity-comes-from-and-how-it-can-do-better-617/</p>

                <p>https://www.seia.org/state-solar-policy/florida-solar</p>

                <p>https://impactsciences.com/featured-news/5-ways-active-transportation-benefits-our-communities/</p>

                <p>http://www.todayifoundout.com/index.php/2014/03/grass-lawns-2/</p>

                <p>https://www.epa.gov/ms-htf/hypoxia-101</p>

                <p>https://theminimalistvegan.com/live-a-more-sustainable-lifestyle/</p>

                <p>https://communitynewspapers.com/kendallgazette/what-they-really-do-miami-dade-dept-of-solid-waste-management/</p>

                <p>https://www.miamidade.gov/global/solidwaste/home.page</p>

                <p>https://blog.repurpose.global/us-waste-exporting-explained/</p>

                <p>https://cleanmanagement.com/about-us/</p>
            </Container>
        </>
    );
}

export default SustainableMiami;